# Travis CI configuration file.

language: php

# 5.4 is required for Codeception.
php:
    - 5.6
    - 7.0

# Use the new container-based infrastructure (it's faster).
sudo: false

matrix:
    include:
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: hhvm
        - php: nightly
    fast_finish: true

before_script:
    # Define vars.
    - export WP_VERSION=master
    - export WP_DEVELOP_DIR=/tmp/wordpress
    - export WP_CORE_DIR=/tmp/wordpress/src
    - export WP_CEPT_SERVER='127.0.0.1:8888'
    # Install WordPress
    - source travis.sh
    - install-wordpress
    # Start up a web server.
    - php -S "$WP_CEPT_SERVER" -t "$WP_CORE_DIR" >/dev/null 2>&1 &
    # Start up the webdriver.
    - phantomjs --webdriver=4444 >/dev/null 2>&1 &
    # Install Codeception and WP Browser.
    # Doing this last gives the webdriver and server time to start up.
    - composer install --prefer-source

script:
    - vendor/bin/wpcept run
    # Run the tests as multisite as well.
    - enable-multisite && vendor/bin/wpcept run

# EOF
