# Travis CI configuration file.

language: php

# 5.4 is required for Codeception.
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - WP_VERSION=master
    - WP_VERSION=4.5
    - WP_VERSION=4.4

# Use the new container-based infrastructure (it's faster).
sudo: false

matrix:
    include:
        # Only run HHVM against trunk.
        - php: hhvm
          env: TRAVISCI_RUN=phpunit WP_VERSION=master
        # Only run nightly against trunk.
        - php: nightly
          env: TRAVISCI_RUN=phpunit WP_VERSION=master
    allow_failures:
        - php: hhvm
        - php: nightly
    fast_finish: true

before_script:
    # Define vars.
    - export WP_DEVELOP_DIR=/tmp/wordpress
    - export WP_CORE_DIR=/tmp/wordpress/src
    - export WP_CEPT_SERVER='localhost:8888'
    # Install WordPress
    - source travis.sh
    - install-wordpress
    # Install Codeception and WP Browser.
    - composer require --prefer-source codeception/codeception lucatume/wp-browser
    # Start up a web server.
    - php -S "$WP_CEPT_SERVER" -t "$WP_CORE_DIR" >/dev/null 2>&1 &
    # Start up the webdriver.
    - phantomjs --webdriver=4444 >/dev/null 2>&1 &
    # Give the server and webdriver some time to start.
    - sleep 5

script:
    - vendor/bin/wpcept run

# EOF
